# Generated by Django 5.2 on 2025-04-07 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del juego')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cognitive_area', models.CharField(choices=[('memoria', 'Memoria'), ('atencion', 'Atención'), ('lenguaje', 'Lenguaje'), ('funcion_ejecutiva', 'Función Ejecutiva'), ('razonamiento', 'Razonamiento')], max_length=20, verbose_name='Área cognitiva')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel de dificultad')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Puntuación')),
                ('time_spent', models.IntegerField(verbose_name='Tiempo empleado (segundos)')),
                ('errors', models.IntegerField(verbose_name='Número de errores')),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='patients.patient')),
            ],
        ),
    ]
