# Generated by Django 5.2 on 2025-04-07 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Paciente (DNI/TIS)')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Edad')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('education_level', models.CharField(choices=[('primaria', 'Educación Primaria'), ('secundaria', 'Educación Secundaria'), ('universidad', 'Educación Universitaria'), ('postgrado', 'Postgrado')], max_length=20, verbose_name='Nivel educativo')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50, verbose_name='Tipo de dato')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_data', to='patients.patient')),
            ],
            options={
                'unique_together': {('patient', 'data_type', 'date_recorded')},
            },
        ),
    ]
